apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:9.1.0
          env:
            - name: ELASTICSEARCH_HOSTS
              value: http://elasticsearch:9200
            - name: NODE_OPTIONS
              value: "--max-old-space-size=512"
            # Encryption keys to stop warnings & enable features
            - name: XPACK_SECURITY_ENCRYPTIONKEY
              value: "9e3f3db4b8e249f4a6b15f9a4e9cde43"
            - name: XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY
              value: "e045417b9a5c4f8cbfda871e5179d184"
            - name: XPACK_REPORTING_ENCRYPTIONKEY
              value: "d6f0dcedb4ac4fa3bb14d6a8e4fbb267"
          ports:
            - containerPort: 5601
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"
            requests:
              memory: "512Mi"
              cpu: "250m"
          readinessProbe:
            httpGet:
              path: /api/status
              port: 5601
            initialDelaySeconds: 90
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/status
              port: 5601
            initialDelaySeconds: 120
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: logging
spec:
  type: NodePort
  selector:
    app: kibana
  ports:
    - port: 5601
      nodePort: 30601
